/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 ./public/bubble.glb 
*/

import { useGLTF } from '@react-three/drei'
import { Mesh } from 'three'

export function BubbleModel(props: {color: string}) {
  // const { nodes, materials } = useGLTF('/bubble.glb')
  const { nodes } = useGLTF('/bubble.glb')
  const {color} = props
  return (
    <group dispose={null} rotation={[0, -Math.PI / 2, 0]}>
      <mesh
        geometry={(nodes.Plane as Mesh).geometry}
        // material={materials.cartoon}
        receiveShadow
        castShadow
      >
        <meshStandardMaterial attach="material" color={color} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/bubble.glb')
